# Generated by Django 4.2.7 on 2023-11-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('comment', models.TextField(max_length=500, verbose_name='Enquiry Message')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time')),
            ],
            options={
                'verbose_name_plural': 'Enquiry Details',
            },
        ),
    ]
